import type { Legend } from './types'

/** Legends of a parsed legends.json; anything that does not look like one yields an empty list. */
export function legendsFromJson(json: unknown): Legend[] {
  const legends = (json as { legends?: unknown } | null)?.legends
  if (!Array.isArray(legends)) return []
  return legends.filter(
    (l): l is Legend => typeof l?.slug === 'string' && typeof l.name === 'string' && Array.isArray(l.cards),
  )
}

/**
 * Loads public/data/legends.json. The file is optional (generated by `npm run import`): a missing or
 * invalid file yields an empty list instead of an error.
 */
export async function loadLegends(): Promise<Legend[]> {
  try {
    const res = await fetch(`${import.meta.env.BASE_URL}data/legends.json`)
    if (!res.ok) return []
    // The dev server answers index.html for a missing file: the JSON parse fails and lands in the catch.
    return legendsFromJson(await res.json())
  } catch {
    return []
  }
}
